### ISSUE TITLE
when will the training code be released?

### ISSUE THREAD

**Issue by IceIce1ce** [it-hao/SFAN#1]
Hi authors,

Thank you for your great code. I hope you can release the training and testing code.

**Comment by it-hao** [comment]
> Hi authors,
> 
> Thank you for your great code. I hope you can release the training and testing code.

I am currently working on my PhD dissertation and will upload all source code as soon as possible.

**Comment by IceIce1ce** [comment]
Thanks for your information.

**Comment by IceIce1ce** [comment]
Hi author, can you upload full code?

**Comment by it-hao** [comment]
> Hi author, can you upload full code?

We have updated the training code. Please note that both our training and testing were based on 256 image patches.

**Comment by IceIce1ce** [comment]
Hi author, thanks for your great code.
